# Intermediate Python
Run the hidden code cell below to import the data used in this course.

In [2]:
# Import the course packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import the two datasets
gapminder = pd.read_csv("datasets/gapminder.csv")
brics = pd.read_csv("datasets/brics.csv")

## Take Notes

Add notes about the concepts you've learned and code cells with code you want to keep.

_Add your notes here_

In [3]:
brics

  country_ab       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

## Explore Datasets
Use the DataFrames imported in the first cell to explore the data and practice your skills!
- Create a loop that iterates through the `brics` DataFrame and prints "The population of {country} is {population} million!". 
- Create a histogram of the life expectancies for countries in Africa in the `gapminder` DataFrame. Make sure your plot has a title, axis labels, and has an appropriate number of bins.
- Simulate 10 rolls of two six-sided dice. If the two dice add up to 7 or 11, print "A win!". If the two dice add up to 2, 3, or 12, print "A loss!". If the two dice add up to any other number, print "Roll again!".

In [4]:
brics.size

25

In [7]:
brics.index = brics["country_ab"]
brics

           country_ab       country    capital    area  population
country_ab
BR                 BR        Brazil   Brasilia   8.516      200.40
RU                 RU        Russia     Moscow  17.100      143.50
IN                 IN         India  New Delhi   3.286     1252.00
CH                 CH         China    Beijing   9.597     1357.00
SA                 SA  South Africa   Pretoria   1.221       52.98

In [9]:
brics = brics.iloc[:,1:5]
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [11]:
brics.loc[["IN"],:]

           country    capital   area  population
country_ab
IN           India  New Delhi  3.286      1252.0